package com.cartadespido.automatizacion.model;

import java.util.Map;

public class Comunas {
    public static final Map<String, String> COMUNAS = Map.ofEntries(
            Map.entry("15101", "Arica"),
            Map.entry("15102", "Camarones"),
            Map.entry("15201", "Putre"),
            Map.entry("15202", "General Lagos"),
            Map.entry("1101", "Iquique"),
            Map.entry("1107", "Alto Hospicio"),
            Map.entry("1401", "Pozo Almonte"),
            Map.entry("1102", "Camiña"),
            Map.entry("1403", "Colchane"),
            Map.entry("1404", "Huara"),
            Map.entry("1405", "Pica"),
            Map.entry("2101", "Antofagasta"),
            Map.entry("2102", "Mejillones"),
            Map.entry("2103", "Sierra Gorda"),
            Map.entry("2104", "Taltal"),
            Map.entry("2201", "Calama"),
            Map.entry("2202", "Ollagüe"),
            Map.entry("2203", "San Pedro de Atacama"),
            Map.entry("2301", "Tocopilla"),
            Map.entry("2302", "María Elena"),
            Map.entry("3101", "Copiapó"),
            Map.entry("3102", "Caldera"),
            Map.entry("3103", "Tierra Amarilla"),
            Map.entry("3201", "Chañaral"),
            Map.entry("3202", "Diego de Almagro"),
            Map.entry("3301", "Vallenar"),
            Map.entry("3302", "Alto del Carmen"),
            Map.entry("3303", "Freirina"),
            Map.entry("3304", "Huasco"),
            Map.entry("4101", "La Serena"),
            Map.entry("4102", "Coquimbo"),
            Map.entry("4103", "Andacollo"),
            Map.entry("4104", "La Higuera"),
            Map.entry("4105", "Paiguano"),
            Map.entry("4106", "Vicuña"),
            Map.entry("4201", "Illapel"),
            Map.entry("4202", "Canela"),
            Map.entry("4203", "Los Vilos"),
            Map.entry("4204", "Salamanca"),
            Map.entry("4301", "Ovalle"),
            Map.entry("4302", "Combarbalá"),
            Map.entry("4303", "Monte Patria"),
            Map.entry("4304", "Punitaqui"),
            Map.entry("4305", "Río Hurtado"),
            Map.entry("5101", "Valparaíso"),
            Map.entry("5102", "Casablanca"),
            Map.entry("5103", "Concón"),
            Map.entry("5104", "Juan Fernández"),
            Map.entry("5105", "Puchuncaví"),
            Map.entry("5106", "Quilpué"),
            Map.entry("5107", "Quintero"),
            Map.entry("5108", "Villa Alemana"),
            Map.entry("5109", "Viña del Mar"),
            Map.entry("5201", "Isla de Pascua"),
            Map.entry("5301", "Los Andes"),
            Map.entry("5302", "Calle Larga"),
            Map.entry("5303", "Rinconada"),
            Map.entry("5304", "San Esteban"),
            Map.entry("5401", "La Ligua"),
            Map.entry("5402", "Cabildo"),
            Map.entry("5403", "Papudo"),
            Map.entry("5404", "Petorca"),
            Map.entry("5405", "Zapallar"),
            Map.entry("5501", "Quillota"),
            Map.entry("5502", "Calera"),
            Map.entry("5503", "Hijuelas"),
            Map.entry("5504", "La Cruz"),
            Map.entry("5505", "Limache"),
            Map.entry("5506", "Nogales"),
            Map.entry("5507", "Olmué"),
            Map.entry("5601", "San Antonio"),
            Map.entry("5602", "Algarrobo"),
            Map.entry("5603", "Cartagena"),
            Map.entry("5604", "El Quisco"),
            Map.entry("5605", "El Tabo"),
            Map.entry("5606", "Santo Domingo"),
            Map.entry("5701", "San Felipe"),
            Map.entry("5702", "Catemu"),
            Map.entry("5703", "Llaillay"),
            Map.entry("5704", "Panquehue"),
            Map.entry("5705", "Putaendo"),
            Map.entry("5706", "Santa María"),
            Map.entry("6101", "Rancagua"),
            Map.entry("6102", "Codegua Gral"),
            Map.entry("6103", "Coinco"),
            Map.entry("6104", "Coltauco"),
            Map.entry("6105", "Doñihue"),
            Map.entry("6106", "Graneros"),
            Map.entry("6107", "Las Cabras"),
            Map.entry("6108", "Machalí"),
            Map.entry("6109", "Malloa"),
            Map.entry("6110", "Mostazal"),
            Map.entry("6111", "Olivar"),
            Map.entry("6112", "Peumo"),
            Map.entry("6113", "Pichidegua"),
            Map.entry("6114", "Quinta de Tilcoco"),
            Map.entry("6115", "Rengo"),
            Map.entry("6116", "Requínoa"),
            Map.entry("6117", "San Vicente"),
            Map.entry("6201", "Pichilemu"),
            Map.entry("6202", "La Estrella"),
            Map.entry("6203", "Litueche"),
            Map.entry("6204", "Marchihue"),
            Map.entry("6205", "Navidad"),
            Map.entry("6206", "Paredones"),
            Map.entry("6301", "San Fernando"),
            Map.entry("6302", "Chépica"),
            Map.entry("6303", "Chimbarongo"),
            Map.entry("6304", "Lolol"),
            Map.entry("6305", "Nancagua"),
            Map.entry("6306", "Palmilla"),
            Map.entry("6307", "Peralillo"),
            Map.entry("6308", "Placilla"),
            Map.entry("6309", "Pumanque"),
            Map.entry("6310", "Santa Cruz"),
            Map.entry("7101", "Talca"),
            Map.entry("7102", "Constitución"),
            Map.entry("7103", "Curepto"),
            Map.entry("7104", "Empedrado"),
            Map.entry("7105", "Maule"),
            Map.entry("7106", "Pelarco"),
            Map.entry("7107", "Pencahue"),
            Map.entry("7108", "Río Claro"),
            Map.entry("7109", "San Clemente"),
            Map.entry("7110", "San Rafael"),
            Map.entry("7201", "Cauquenes"),
            Map.entry("7202", "Chanco"),
            Map.entry("7203", "Pelluhue"),
            Map.entry("7301", "Curicó"),
            Map.entry("7302", "Hualañé"),
            Map.entry("7303", "Licantén"),
            Map.entry("7304", "Molina"),
            Map.entry("7305", "Rauco"),
            Map.entry("7306", "Romeral"),
            Map.entry("7307", "Sagrada Familia"),
            Map.entry("7308", "Teno"),
            Map.entry("7309", "Vichuquén"),
            Map.entry("7401", "Linares"),
            Map.entry("7402", "Colbún"),
            Map.entry("7403", "Longaví"),
            Map.entry("7404", "Parral"),
            Map.entry("7405", "Retiro"),
            Map.entry("7406", "San Javier"),
            Map.entry("7407", "Villa Alegre"),
            Map.entry("7408", "Yerbas Buenas"),
            Map.entry("8101", "Concepción"),
            Map.entry("8102", "Coronel"),
            Map.entry("8103", "Chiguayante"),
            Map.entry("8104", "Florida"),
            Map.entry("8105", "Hualqui"),
            Map.entry("8106", "Lota"),
            Map.entry("8107", "Penco"),
            Map.entry("8108", "San Pedro de la Paz"),
            Map.entry("8109", "Santa Juana"),
            Map.entry("8110", "Talcahuano"),
            Map.entry("8111", "Tomé"),
            Map.entry("8112", "H ualpén"),
            Map.entry("8201", "Lebu"),
            Map.entry("8202", "Arauco"),
            Map.entry("8203", "Cañete"),
            Map.entry("8204", "Contulmo"),
            Map.entry("8205", "Curanilahue"),
            Map.entry("8206", "Los Alamos"),
            Map.entry("8207", "Tirúa"),
            Map.entry("8301", "Los Angeles"),
            Map.entry("8302", "Antuco"),
            Map.entry("8303", "Cabrero"),
            Map.entry("8304", "Laja"),
            Map.entry("8305", "Mulchén"),
            Map.entry("8306", "Nacimiento"),
            Map.entry("8307", "Negrete"),
            Map.entry("8308", "Quilaco"),
            Map.entry("8309", "Quilleco"),
            Map.entry("8310", "San Rosendo"),
            Map.entry("8311", "Santa Bárbara"),
            Map.entry("8312", "Tucapel"),
            Map.entry("8313", "Yumbel"),
            Map.entry("8314", "Alto Biobío"),
            Map.entry("8401", "Chillán"),
            Map.entry("8402", "Bulnes"),
            Map.entry("8403", "Cobquecura"),
            Map.entry("8404", "Coelemu"),
            Map.entry("8405", "Coihueco"),
            Map.entry("8406", "Chillán Viejo"),
            Map.entry("8407", "El Carmen"),
            Map.entry("8408", "Ninhue"),
            Map.entry("8409", "Ñiquén"),
            Map.entry("8410", "Pemuco"),
            Map.entry("8411", "Pinto"),
            Map.entry("8412", "Portezuelo"),
            Map.entry("8413", "Quillón"),
            Map.entry("8414", "Quirihue"),
            Map.entry("8415", "Ránquil"),
            Map.entry("8416", "San Carlos"),
            Map.entry("8417", "San Fabián"),
            Map.entry("8418", "San Ignacio"),
            Map.entry("8419", "San Nicolás"),
            Map.entry("8420", "Treguaco"),
            Map.entry("8421", "Yungay"),
            Map.entry("9101", "Temuco"),
            Map.entry("9102", "Carahue"),
            Map.entry("9103", "Cunco"),
            Map.entry("9104", "Curarrehue"),
            Map.entry("9105", "Freire"),
            Map.entry("9106", "Galvarino"),
            Map.entry("9107", "Gorbea"),
            Map.entry("9108", "Lautaro"),
            Map.entry("9109", "Loncoche"),
            Map.entry("9110", "Melipeuco"),
            Map.entry("9111", "Nueva Imperial"),
            Map.entry("9112", "Padre Las Casas"),
            Map.entry("9113", "Perquenco"),
            Map.entry("9114", "Pitrufquén"),
            Map.entry("9115", "Pucón"),
            Map.entry("9116", "Saavedra"),
            Map.entry("9117", "Teodoro Schmidt"),
            Map.entry("9118", "Toltén"),
            Map.entry("9119", "Vilcún"),
            Map.entry("9120", "Villarrica"),
            Map.entry("9121", "Cholchol"),
            Map.entry("9201", "Angol"),
            Map.entry("9202", "Collipulli"),
            Map.entry("9203", "Curacautín"),
            Map.entry("9204", "Ercilla"),
            Map.entry("9205", "Lonquimay"),
            Map.entry("9206", "Los Sauces"),
            Map.entry("9207", "Lumaco"),
            Map.entry("9208", "Purén"),
            Map.entry("9209", "Renaico"),
            Map.entry("9210", "Traiguén"),
            Map.entry("9211", "Victoria"),
            Map.entry("14101", "Valdivia"),
            Map.entry("14102", "Corral"),
            Map.entry("14103", "Lanco"),
            Map.entry("14104", "Los Lagos"),
            Map.entry("14105", "Máfil"),
            Map.entry("14106", "Mariquina"),
            Map.entry("14107", "Paillaco"),
            Map.entry("14108", "Panguipulli"),
            Map.entry("14201", "La Unión"),
            Map.entry("14202", "Futrono"),
            Map.entry("14203", "Lago Ranco"),
            Map.entry("14204", "Río Bueno"),
            Map.entry("10101", "Puerto Montt"),
            Map.entry("10102", "Calbuco"),
            Map.entry("10103", "Cochamó"),
            Map.entry("10104", "Fresia"),
            Map.entry("10105", "Frutillar"),
            Map.entry("10106", "Los Muermos"),
            Map.entry("10107", "Llanquihue"),
            Map.entry("10108", "Maullín"),
            Map.entry("10109", "Puerto Varas"),
            Map.entry("10201", "Castro"),
            Map.entry("10202", "Ancud"),
            Map.entry("10203", "Chonchi"),
            Map.entry("10204", "Curaco de Vélez"),
            Map.entry("10205", "Dalcahue"),
            Map.entry("10206", "Puqueldón"),
            Map.entry("10207", "Queilén"),
            Map.entry("10208", "Quellón"),
            Map.entry("10209", "Quemchi"),
            Map.entry("10210", "Quinchao"),
            Map.entry("10301", "Osorno"),
            Map.entry("10302", "Puerto Octay"),
            Map.entry("10303", "Purranque"),
            Map.entry("10304", "Puyehue"),
            Map.entry("10305", "Río Negro"),
            Map.entry("10306", "San Juan de la Costa"),
            Map.entry("10307", "San Pablo"),
            Map.entry("10401", "Chaitén"),
            Map.entry("10402", "Futaleufú"),
            Map.entry("10403", "Hualaihué"),
            Map.entry("10404", "Palena"),
            Map.entry("11101", "Coihaique"),
            Map.entry("11102", "Lago Verde Carlos Ibáñez"),
            Map.entry("11201", "Aisén"),
            Map.entry("11202", "Cisnes"),
            Map.entry("11203", "Guaitecas"),
            Map.entry("11301", "Cochrane"),
            Map.entry("11302", "O'Higgins"),
            Map.entry("11303", "Tortel"),
            Map.entry("11401", "Chile Chico"),
            Map.entry("11402", "Río Ibáñez"),
            Map.entry("12101", "Punta Arenas"),
            Map.entry("12102", "Laguna Blanca y de la Antártica"),
            Map.entry("12103", "Río Verde Chilena"),
            Map.entry("12104", "San Gregorio"),
            Map.entry("12201", "Cabo de Hornos"),
            Map.entry("12202", "Antártica"),
            Map.entry("12301", "Porvenir"),
            Map.entry("12302", "Primavera"),
            Map.entry("12303", "Timaukel"),
            Map.entry("12401", "Natales"),
            Map.entry("12402", "Torres del Paine"),
            Map.entry("13101", "Santiago"),
            Map.entry("13102", "Cerrillos"),
            Map.entry("13103", "Cerro Navia"),
            Map.entry("13104", "Conchalí"),
            Map.entry("13105", "El Bosque"),
            Map.entry("13106", "Estación Central"),
            Map.entry("13107", "Huechuraba"),
            Map.entry("13108", "Independencia"),
            Map.entry("13109", "La Cisterna"),
            Map.entry("13110", "La Florida"),
            Map.entry("13111", "La Granja"),
            Map.entry("13112", "La Pintana"),
            Map.entry("13113", "La Reina"),
            Map.entry("13114", "Las Condes"),
            Map.entry("13115", "Lo Barnechea"),
            Map.entry("13116", "Lo Espejo"),
            Map.entry("13117", "Lo Prado"),
            Map.entry("13118", "Macul"),
            Map.entry("13119", "Maipú"),
            Map.entry("13120", "Ñuñoa"),
            Map.entry("13121", "Pedro  Aguirre Cerda"),
            Map.entry("13122", "Peñalolén"),
            Map.entry("13123", "Providencia"),
            Map.entry("13124", "Pudahuel"),
            Map.entry("13125", "Quilicura"),
            Map.entry("13126", "Quinta Normal"),
            Map.entry("13127", "Recoleta"),
            Map.entry("13128", "Renca"),
            Map.entry("13129", "San Joaquín"),
            Map.entry("13130", "San Miguel"),
            Map.entry("13131", "San Ramón"),
            Map.entry("13132", "Vitacura"),
            Map.entry("13201", "Puente Alto"),
            Map.entry("13202", "Pirque"),
            Map.entry("13203", "San José de Maipo"),
            Map.entry("13301", "Colina"),
            Map.entry("13302", "Lampa"),
            Map.entry("13303", "Tiltil"),
            Map.entry("13401", "San Bernardo"),
            Map.entry("13402", "Buin"),
            Map.entry("13403", "Calera de Tango"),
            Map.entry("13404", "Paine"),
            Map.entry("13501", "Melipilla"),
            Map.entry("13502", "Alhué"),
            Map.entry("13503", "Curacaví"),
            Map.entry("13504", "María Pinto"),
            Map.entry("13505", "San Pedro"),
            Map.entry("13601", "Talagante"),
            Map.entry("13602", "El Monte"),
            Map.entry("13603", "Isla de Maipo"),
            Map.entry("13604", "Padre Hurtado"),
            Map.entry("13605", "Peñaflor")
    );
}