package com.cartadespido.automatizacion.model;

import java.util.Map;

public class Nacionalidades {
    public static final Map<String, String> NACIONALIDADES = Map.ofEntries(
            Map.entry("501", "AFGANA"),
            Map.entry("1003", "AFRICA"),
            Map.entry("1004", "AFRICA DEL SUDOESTE"),
            Map.entry("1005", "ALASKA"),
            Map.entry("601", "ALBANES"),
            Map.entry("602", "ALEMANA"),
            Map.entry("603", "ANDORRANA"),
            Map.entry("402", "ANGOLEÑA"),
            Map.entry("1018", "ANTILLAS NEERLANDESAS"),
            Map.entry("999", "APATRIDA"),
            Map.entry("502", "ARABE SAUDITA"),
            Map.entry("513", "ARABE UNIDA"),
            Map.entry("403", "ARGELINA"),
            Map.entry("301", "ARGENTINA"),
            Map.entry("546", "ARMENIO"),
            Map.entry("701", "AUSTRALIANA"),
            Map.entry("604", "AUSTRIACA"),
            Map.entry("545", "AZERBAIYANO"),
            Map.entry("202", "BAHAMES"),
            Map.entry("445", "BANTU"),
            Map.entry("203", "BARBADENSE"),
            Map.entry("702", "BELAN"),
            Map.entry("1033", "BELAU"),
            Map.entry("605", "BELGA"),
            Map.entry("204", "BELICEÑO"),
            Map.entry("404", "BENINES"),
            Map.entry("642", "BIELORUSA"),
            Map.entry("505", "BIRMANA"),
            Map.entry("302", "BOLIVIANA"),
            Map.entry("405", "BOPHUTHATSWANI"),
            Map.entry("406", "BOTSWANES"),
            Map.entry("303", "BRASILEÑA"),
            Map.entry("544", "BRITANICA"),
            Map.entry("625", "BRITANICA"),
            Map.entry("606", "BULGARA"),
            Map.entry("407", "BURUNDIANA"),
            Map.entry("507", "BUTHANES"),
            Map.entry("408", "CABOVERDIANA"),
            Map.entry("552", "CAMBOYANA"),
            Map.entry("409", "CAMERUNES"),
            Map.entry("101", "CANADIENSE"),
            Map.entry("1058", "CEILAN"),
            Map.entry("438", "CENTROAFRICANA"),
            Map.entry("414", "CHADIANA"),
            Map.entry("655", "CHECA"),
            Map.entry("607", "CHECOSLOVACA"),
            Map.entry("320", "CHILENA"),
            Map.entry("511", "CHINA POPULAR"),
            Map.entry("512", "CHIPRIOTA"),
            Map.entry("535", "CINGALESA"),
            Map.entry("410", "CISKEINA"),
            Map.entry("304", "COLOMBIANA"),
            Map.entry("411", "COMORANA"),
            Map.entry("412", "CONGOLEÑO"),
            Map.entry("508", "COREANA"),
            Map.entry("509", "COREANA"),
            Map.entry("205", "COSTARRICENSE"),
            Map.entry("643", "CROATA"),
            Map.entry("206", "CUBANA"),
            Map.entry("1075", "CURLANDIA"),
            Map.entry("1076", "DAHOMEY"),
            Map.entry("1077", "DALMACIA"),
            Map.entry("608", "DANESA"),
            Map.entry("201", "DE ANTIGUA Y BARBUDA"),
            Map.entry("503", "DE BAHREIN"),
            Map.entry("504", "DE BANGLADESH"),
            Map.entry("645", "DE BOSNIA Y HERZEGOVINA"),
            Map.entry("506", "DE BRUNEI DARUS-SALAM"),
            Map.entry("457", "DE BURKINA FASO"),
            Map.entry("415", "DE DJIBOUTI"),
            Map.entry("207", "DE DOMINICA"),
            Map.entry("703", "DE FIJI"),
            Map.entry("217", "DOMINICANA"),
            Map.entry("305", "ECUATORIANA"),
            Map.entry("416", "EGIPCIA"),
            Map.entry("1085", "EIRE"),
            Map.entry("1087", "ELLICE"),
            Map.entry("459", "ERITREA"),
            Map.entry("633", "ESCOCESA"),
            Map.entry("657", "ESLOVACA"),
            Map.entry("644", "ESLOVENA"),
            Map.entry("609", "ESPAÑOLA"),
            Map.entry("102", "ESTADOUNIDENSE"),
            Map.entry("637", "ESTONIO"),
            Map.entry("417", "ETIOPE"),
            Map.entry("222", "FED. SAINTS KITTS"),
            Map.entry("527", "FEDERACION DE MALASI"),
            Map.entry("514", "FILIPINO"),
            Map.entry("610", "FINLANDESA"),
            Map.entry("611", "FRANCESA"),
            Map.entry("715", "FRANCESA"),
            Map.entry("418", "GABONES"),
            Map.entry("1109", "GALES"),
            Map.entry("419", "GAMBIANO"),
            Map.entry("420", "GANES"),
            Map.entry("547", "GEORGIANA"),
            Map.entry("1113", "GIBRALTAR"),
            Map.entry("1115", "GRANADINO"),
            Map.entry("209", "GRANADINO"),
            Map.entry("612", "GRIEGA"),
            Map.entry("210", "GUATEMALTECA"),
            Map.entry("1119", "GUAYANA FRANCESA"),
            Map.entry("1120", "GUAYANA HOLANDESA"),
            Map.entry("421", "GUINA"),
            Map.entry("1124", "GUINEA PORTUGUESA"),
            Map.entry("422", "GUINENSE BISSAU"),
            Map.entry("423", "GUINENSE ECUATORIAL"),
            Map.entry("306", "GUYANESA"),
            Map.entry("211", "HAITIANA"),
            Map.entry("613", "HOLANDESA"),
            Map.entry("212", "HONDUREÑA"),
            Map.entry("614", "HUNGARA"),
            Map.entry("1131", "IMPERIO CENTROAFRICANA"),
            Map.entry("515", "INDIA"),
            Map.entry("516", "INDONESIA"),
            Map.entry("518", "IRANI"),
            Map.entry("517", "IRAQUI"),
            Map.entry("615", "IRLANDESA"),
            Map.entry("1139", "ISLA ANGUILLA"),
            Map.entry("1140", "ISLA ARUBA"),
            Map.entry("1141", "ISLA ASCENCION"),
            Map.entry("1142", "ISLA CERDENA"),
            Map.entry("1143", "ISLA CORCEGA"),
            Map.entry("1144", "ISLA CRETA"),
            Map.entry("1145", "ISLA CURAZAO"),
            Map.entry("1146", "ISLA DE PASCUA"),
            Map.entry("1147", "ISLA GROENLANDIA"),
            Map.entry("1148", "ISLA GUADALCANAL"),
            Map.entry("1149", "ISLA GUADALUPE"),
            Map.entry("1150", "ISLA GUAM"),
            Map.entry("1151", "ISLA IWOJIMA"),
            Map.entry("1152", "ISLA JAVA"),
            Map.entry("1153", "ISLA KIUSIU"),
            Map.entry("1154", "ISLA LUZON"),
            Map.entry("1155", "ISLA MARTINICA"),
            Map.entry("1156", "ISLA MINDANAO"),
            Map.entry("1157", "ISLA MONTSERRAT"),
            Map.entry("519", "ISRAELI"),
            Map.entry("617", "ITALIANA"),
            Map.entry("213", "JAMAICANA"),
            Map.entry("520", "JAPONESA"),
            Map.entry("521", "JORDANA"),
            Map.entry("523", "KATAR"),
            Map.entry("548", "KAZAKJASTANA"),
            Map.entry("424", "KENYATA"),
            Map.entry("551", "KIRGI"),
            Map.entry("704", "KIRIBATI"),
            Map.entry("522", "KMER"),
            Map.entry("1282", "KOWEIT"),
            Map.entry("524", "KUWAITI"),
            Map.entry("525", "LAOSIANA"),
            Map.entry("1285", "LAS ANTILLAS"),
            Map.entry("425", "LESOTA"),
            Map.entry("636", "LETONESA"),
            Map.entry("526", "LIBANESA"),
            Map.entry("426", "LIBERIANA"),
            Map.entry("427", "LIBIA"),
            Map.entry("618", "LIECHTENSTEIN"),
            Map.entry("638", "LITUANA"),
            Map.entry("619", "LUXEMBURGUESA"),
            Map.entry("541", "MACAO"),
            Map.entry("656", "MACEDONIA"),
            Map.entry("542", "MALASIA"),
            Map.entry("429", "MALAWI"),
            Map.entry("528", "MALDIVAS"),
            Map.entry("428", "MALGACHE"),
            Map.entry("430", "MALI"),
            Map.entry("620", "MALTA"),
            Map.entry("413", "MARFILEÑA"),
            Map.entry("431", "MARROQUI"),
            Map.entry("1302", "MASCATE Y OMAN"),
            Map.entry("432", "MAURICIA"),
            Map.entry("433", "MAURITANIA"),
            Map.entry("103", "MEXICANA"),
            Map.entry("705", "MICRONESIA"),
            Map.entry("529", "MOGOL"),
            Map.entry("639", "MOLDAVA"),
            Map.entry("670", "MOLDOVA"),
            Map.entry("621", "MONEGASCA"),
            Map.entry("1310", "MONTE ATHOS"),
            Map.entry("648", "MONTENEGRINA"),
            Map.entry("434", "MOZAMBIQUE@A"),
            Map.entry("435", "NAMIBIA"),
            Map.entry("706", "NAURU"),
            Map.entry("707", "NEOZELANDESA"),
            Map.entry("530", "NEPALESA"),
            Map.entry("1318", "NGWANE"),
            Map.entry("214", "NICARAGUENSE"),
            Map.entry("437", "NIGERIANA"),
            Map.entry("436", "NIGERINA"),
            Map.entry("622", "NORUEGA"),
            Map.entry("708", "NOVO GUINEANA"),
            Map.entry("1325", "NUEVAS HEBRIDAS"),
            Map.entry("1326", "OCEANIA"),
            Map.entry("531", "OMANI"),
            Map.entry("532", "PAKISTANI"),
            Map.entry("540", "PALESTINA"),
            Map.entry("215", "PANAMEÑA"),
            Map.entry("307", "PARAGUAYA"),
            Map.entry("308", "PERUANA"),
            Map.entry("623", "POLACA"),
            Map.entry("216", "PORTORRIQUENSE"),
            Map.entry("624", "PORTUGUESA"),
            Map.entry("543", "QATAR"),
            Map.entry("1350", "REPUBLICA COMORAS"),
            Map.entry("1357", "REPUBLICA MALGACHE"),
            Map.entry("1360", "RHODESIA"),
            Map.entry("626", "RUMANA"),
            Map.entry("640", "RUSA"),
            Map.entry("439", "RWANDA"),
            Map.entry("208", "SALVADOREÑA"),
            Map.entry("710", "SAMOANA"),
            Map.entry("221", "SAN CRISTOBAL Y NEVI"),
            Map.entry("627", "SAN MARINA"),
            Map.entry("218", "SANTA LUCIA"),
            Map.entry("440", "SANTO TOME Y PRINCIPE"),
            Map.entry("441", "SENEGANI"),
            Map.entry("646", "SERBIA"),
            Map.entry("442", "SEYCHELLES"),
            Map.entry("641", "SIBERIANA"),
            Map.entry("443", "SIERRALEONES"),
            Map.entry("1388", "SIKKIM"),
            Map.entry("533", "SINGAPURENSE"),
            Map.entry("534", "SIRIA"),
            Map.entry("450", "SISKEYANA"),
            Map.entry("444", "SOMALI"),
            Map.entry("446", "SUDAFRICANA"),
            Map.entry("447", "SUDANESA"),
            Map.entry("628", "SUECA"),
            Map.entry("629", "SUIZA"),
            Map.entry("309", "SURINAMEÑA"),
            Map.entry("1404", "SVALBARD"),
            Map.entry("536", "TAILANDESA"),
            Map.entry("510", "TAIWANES"),
            Map.entry("448", "TANZANIA"),
            Map.entry("550", "THASJANA"),
            Map.entry("449", "TOGOLESA"),
            Map.entry("711", "TONGALESA"),
            Map.entry("1413", "TRANSJORDANIA"),
            Map.entry("220", "TRINITENSE"),
            Map.entry("458", "TUNEZ"),
            Map.entry("1417", "TUNISIA"),
            Map.entry("537", "TURCA"),
            Map.entry("712", "TUVALU"),
            Map.entry("635", "UCRANIANA"),
            Map.entry("451", "UGANDESA"),
            Map.entry("310", "URUGUAYA"),
            Map.entry("549", "UZBEKA"),
            Map.entry("713", "VANUATU"),
            Map.entry("631", "VATICANA"),
            Map.entry("453", "VENDA"),
            Map.entry("311", "VENEZOLANA"),
            Map.entry("219", "VICENTEÑA"),
            Map.entry("538", "VIETNAMITA"),
            Map.entry("401", "VOLTEÑA"),
            Map.entry("1431", "YEMEN DEL NORTE"),
            Map.entry("1432", "YEMEN DEL SUR"),
            Map.entry("539", "YEMENITA"),
            Map.entry("632", "YUGOSLAVA"),
            Map.entry("454", "ZAIREÑA"),
            Map.entry("455", "ZAMBIANA"),
            Map.entry("456", "ZIMBABWENSE")
    );
}
